import {
  ShoppingCart,
  Utensils,
  Car,
  Home,
  Heart,
  Briefcase,
  Gift,
  DollarSign,
  PiggyBank,
  CreditCard,
  Wallet,
  AlarmClock,
  Calendar,
  Check,
  Folder,
  Star,
  User,
  X,
  Salad,
  Beer,
  Book,
  Bus,
  Camera,
  Candy,
  Cloud,
  Coffee,
  Coins,
  Dumbbell,
  Eye,
  Film,
  Gamepad,
  Globe,
  Headphones,
  Key,
  Laptop,
  Leaf,
  Lightbulb,
  Lock,
  Map,
  Music,
  Pen,
  Phone,
  Plane,
  Receipt,
  Shield,
  ShoppingBag,
  Train,
  Tv,
  Watch,
  Plus,
} from 'lucide-react'

export const LucideIconList = [
  { name: 'ShoppingCart', Component: ShoppingCart },
  { name: 'Utensils', Component: Utensils },
  { name: 'Car', Component: Car },
  { name: 'Home', Component: Home },
  { name: 'Heart', Component: Heart },
  { name: 'Briefcase', Component: Briefcase },
  { name: 'Gift', Component: Gift },
  { name: 'DollarSign', Component: DollarSign },
  { name: 'PiggyBank', Component: PiggyBank },
  { name: 'CreditCard', Component: CreditCard },
  { name: 'Wallet', Component: Wallet },
  { name: 'AlarmClock', Component: AlarmClock },
  { name: 'Calendar', Component: Calendar },
  { name: 'Check', Component: Check },
  { name: 'Folder', Component: Folder },
  { name: 'Star', Component: Star },
  { name: 'User', Component: User },
  { name: 'X', Component: X },
  { name: 'Salad', Component: Salad },
  { name: 'Beer', Component: Beer },
  { name: 'Book', Component: Book },
  { name: 'Bus', Component: Bus },
  { name: 'Camera', Component: Camera },
  { name: 'Candy', Component: Candy },
  { name: 'Cloud', Component: Cloud },
  { name: 'Coffee', Component: Coffee },
  { name: 'Coins', Component: Coins },
  { name: 'Dumbbell', Component: Dumbbell },
  { name: 'Eye', Component: Eye },
  { name: 'Film', Component: Film },
  { name: 'Gamepad', Component: Gamepad },
  { name: 'Globe', Component: Globe },
  { name: 'Headphones', Component: Headphones },
  { name: 'Key', Component: Key },
  { name: 'Laptop', Component: Laptop },
  { name: 'Leaf', Component: Leaf },
  { name: 'Lightbulb', Component: Lightbulb },
  { name: 'Lock', Component: Lock },
  { name: 'Map', Component: Map },
  { name: 'Music', Component: Music },
  { name: 'Pen', Component: Pen },
  { name: 'Phone', Component: Phone },
  { name: 'Plane', Component: Plane },
  { name: 'Receipt', Component: Receipt },
  { name: 'Shield', Component: Shield },
  { name: 'ShoppingBag', Component: ShoppingBag },
  { name: 'Train', Component: Train },
  { name: 'Tv', Component: Tv },
  { name: 'Watch', Component: Watch },
  { name: 'Plus', Component: Plus },
] as const

export type LucideIconName = (typeof LucideIconList)[number]['name']
